fission-codes/fission-server

- flake.nix
PostgreSQL required in Nix Flake to get a reproducable build
N/A
> Demonstrate the code is solid. Which commands did you test with and what are the expected results?
Run `nix develop && cargo build`
> Which tests have you added or updated? Do the tests cover all of the changes included in this PR?
N/A
```
"CoreFoundation" "-framework" "Security" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/nix/store/k1gfg33vvjzz1gamjjf00pw7q4dmdfqq-rust-default-1.71.0-nightly-2023-04-24/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/expede/Documents/Work/Fission/fission-server/target/debug/deps/fission_server_app-71325f1c108c2380" "-Wl,-dead_strip" "-nodefaultlibs"
= note: ld: library not found for -lpq
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
error: could not …
```
> fix: Add PostgreSQL to Nix Flake

- .envrc
- .gitignore
- flake.nix
Getting postgresql running with diesel in dev mode in diverse environments is a bit tricky. This is an attempt to sidestep some of that, by creating a default database locally (in the `fission-server/.pg/` directory) and providing documentation on how to run a local database with permissive local auth (vs e.g. homebrew's relatively restrictive auth).
This doesn't automatically start the service because nix-shell doesn't appear to have a good way to manage processes, nor does it handle gracefully the case where a developer has a postgresql server already running on port 5432. However, for many it'll simplify the development process, and we can work on handling those edge cases better.'
This PR also adds a .envrc that will automatically be picked up by dotenv and preserve the user's shell …
> feat: add database initialization to nix flake and some direnv helpers

- .rustfmt.toml
This ensures the auto-generated schema.rs from diesel-cli doesn't fail the formatting lint.
> chore: skip formatting generated files

- Cargo.lock
- fission-server/Cargo.toml
- fission-server/config/settings.toml
- fission-server/docs/specs/latest.json
- fission-server/src/db/connection.rs
- fission-server/src/db/mod.rs
- fission-server/src/docs.rs
- fission-server/src/main.rs
- fission-server/src/router.rs
- fission-server/src/routes/account.rs
- fission-server/src/routes/auth.rs
- fission-server/src/routes/health.rs
- fission-server/src/settings.rs
- flake.lock
Resolves https://github.com/fission-codes/fission-server/issues/119
This also adds a background task that hits the endpoint every 5 seconds, killing the server if the healthcheck fails.
> Extend /healthcheck to test database connectivity and schema version

- Cargo.lock
- Cargo.toml
- fission-server/Cargo.toml
- fission-server/src/routes/health.rs
- rust-toolchain.toml
There's a couple of things here, to hopefully fix all of the cargo warnings + get CI running again.
- use the new feature resolver
- correctly configure the dev profile
- switch to stable
- pin ucan and ucan-key-support to the required versions
- run `cargo update`
> Misc. workspace improvements

- Cargo.lock
- fission-server/Cargo.toml
- fission-server/src/app_state.rs
- fission-server/src/router.rs
- fission-server/src/routes/mod.rs
- fission-server/src/routes/ws.rs
I haven't yet found a good way to test axum handlers that upgrade to a websocket connection yet, and we're probably need to do e2e testing against a server that actually runs and binds to connections.
This has been manually tested using ts-odd and AWAKE by hacking it up to change the endpoints it hits for device linking.
> feat: implement websocket relay for account linking

- fission-server/src/settings.rs
Small change to allow settings the IPFS peers via an environment variable.
> feat: allow ipfs.peers config to be set via env var

- Cargo.lock
- Cargo.toml
- fission-server/src/docs.rs
- fission-server/src/middleware/logging.rs
- fission-server/src/models/account.rs
- fission-server/src/routes/doh.rs
- fission-server/src/routes/health.rs
- fission-server/src/routes/volume.rs
- flake.nix
- Added a `utoipa::path` to the `create_volume` handler
- Updated flake so postgres works in NixOS
- Replaced ucan path dependencies with actual UCAN versions (@blaine this would still cause a runtime error, right? What's the github URL that I could depend on?)
> chore: Add `create_volume` to swagger docs

- Cargo.lock
- Cargo.toml
- fission-server/Cargo.toml
- fission-server/src/app_state.rs
- fission-server/src/lib.rs
- fission-server/src/main.rs
- fission-server/src/models/account.rs
- fission-server/src/models/email_verification.rs
- fission-server/src/models/volume.rs
- fission-server/src/router.rs
- fission-server/src/routes/account.rs
- fission-server/src/routes/auth.rs
- fission-server/src/routes/doh.rs
- fission-server/src/routes/health.rs
- fission-server/src/routes/ipfs.rs
- fission-server/src/routes/volume.rs
- fission-server/src/routes/ws.rs
- fission-server/src/test_utils/mod.rs
- fission-server/src/test_utils/test_context.rs
- fission-server/src/test_utils/test_ipfs_database.rs
- fission-server/src/traits.rs
- abstracts out an `IpfsDatabase` trait, so we can run tests without having to run `kubo` next to them
- also collects all "abstract" server state into a single parameter `S: ServerSetup`, which can either be `TestSetup` or `ProdSetup` and use the the correct implementations of `IpfsDatabase` and `VerificationCodeSender` respectively
- adjusted `VerificationCodeSender` to be used via `ServerSetup` instead of as a `dyn trait`
This should make CI work again :tada:
> refactor: Abstract IPFS persistance

- design/api.md
[:scroll: Preview](https://github.com/fission-codes/fission-server/blob/matheus23/api-updates-1/design/api.md)
Major changes:
- ~~Email verifications are associated with a DID now. You can only make use of an email code if you also control the associated DID (or have delegated access).~~ Nevermind. This over-complicates things. Reverted.
- ~~Email verifications now use `verification/...` abilities~~ Nope. No UCAN-based auth on `/email/verify` or `POST /account`
- All capability resources are now *always* DIDs, and essentially mimic the `sub` field from the newer UCAN 1.0 spec.
- The `fetch-capabilities` RPC was changed into a simpler `GET /capabilities` (essentially), and I introduced a `capability/find` ability for it.
- Requests are always passed in the body, never in UCANs as facts. …
> More work on the API spec

- Cargo.lock
- Cargo.toml
- fission-core/src/capabilities.rs
- fission-core/src/capabilities/fission.rs
- fission-core/src/capabilities/indexing.rs
- fission-core/src/common.rs
- fission-server/Cargo.toml
- fission-server/migrations/2023-10-23-163251_ucans_indexer/down.sql
- fission-server/migrations/2023-10-23-163251_ucans_indexer/up.sql
- fission-server/src/db/connection.rs
- fission-server/src/db/schema.rs
- fission-server/src/models/account.rs
- fission-server/src/models/capability_indexing.rs
- fission-server/src/models/mod.rs
- fission-server/src/router.rs
- fission-server/src/routes/account.rs
- fission-server/src/routes/auth.rs
- fission-server/src/routes/capability_indexing.rs
- fission-server/src/routes/mod.rs
- fission-server/src/test_utils/mod.rs
- fission-server/src/test_utils/test_context.rs
- fission-server/src/test_utils/test_ipfs_database.rs
Implements the [`GET /api/v0/capabilities` route](https://github.com/fission-codes/fission-server/blob/main/design/api.md#get-apiv0capabilities).
This allows you to get all UCANs that point to the provided DID (provided in the authorization UCAN as the `capability/fetch` capability resource) as the audience.
The UCAN server will do this caching anyways - and it's useful to give access to this data to the user, so e.g. you can log in to another device very easily, in case you're using a device-syncing passkey.
Closes #182 
Closes #183
> `/api/v0/capabilities` route

- Cargo.lock
- fission-core/Cargo.toml
- fission-server/Cargo.toml
- fission-server/config/settings.toml
- fission-server/src/app_state.rs
- fission-server/src/dns/authority.rs
- fission-server/src/dns/mod.rs
- fission-server/src/dns/response.rs
- fission-server/src/dns/response_handler.rs
- fission-server/src/dns/user_dids.rs
- fission-server/src/extract/authority.rs
- fission-server/src/extract/doh.rs
- fission-server/src/main.rs
- fission-server/src/models/capability_indexing.rs
- fission-server/src/routes/account.rs
- fission-server/src/routes/auth.rs
- fission-server/src/routes/doh.rs
- fission-server/src/settings.rs
- fission-server/src/test_utils/test_context.rs
- Also reworking how DID data is served for users.
- Updated to latest hickory-dns
- Removed volume-related DNS tests (for now)
- Do request forwarding to cloudflare for external requests
- Enables working with the DNS server hosting data under the "localhost" TLD locally.
> feat: Serve the server's DID via DNS

- Cargo.lock
- fission-server/Cargo.toml
- fission-server/src/main.rs
- fission-server/src/tracer.rs
I looked into upgrading `axum` to `0.7` earlier today. We're blocked on doing that until a few upstream dependencies update their versions of `hyper` and `http`, but since we'll need to upgrade `opentelemetry` when we do that anyway, I thought I'd push those changes now.
> Run `cargo update` and upgrade opentelemetry to 0.20

- .gitignore
- flake.lock
- flake.nix
This PR adds a `packages.default` section to `flake.nix` for building fission server as a nix package. I've also bumped the nix version to 23.11 (from 23.05).
You should be able to run `nix build .` and have the resulting binaries in `./result/bin`
> chore: add nix package

- design/api.md
- fission-cli/src/lib.rs
- fission-server/src/extract/authority.rs
- fission-server/src/models/email_verification.rs
- fission-server/src/test_utils/route_builder.rs
Main issue: Fix using a comma as separator between items in the `ucans` header value instead of just whitespace.
Also:
- Fix `design/api.md` docs: The `code` parameter in the email verification request is a `string`, not a `number`
- The verification code should actually be 6 digits, if it's printed like that.
> fix: separator to adhere to ucan bearer token spec

- design/api.md
- fission-server/src/models/capability_indexing.rs
- fission-server/src/routes/capability_indexing.rs
This introduces some tests to `models/capability_indexing.rs` including a test that would've failed previously.
Previously we returned any UCANs that match up via issuer/audience, irrespective of whether they refer to each other in the `prf` array or whether they talk about the same capability.
Now, we make sure that they're talking about exactly the same resource (in the capability).
This needs to be improved in the future to also check for e.g. the `ucan:<...>` scheme, unless UCAN 1.0 comes out first.
We don't actually make use of the `prf` array, anticipating its deprecation in UCAN 1.0.
> feat: Narrow down capability indexing

- Cargo.lock
- fission-cli/src/cli.rs
- fission-core/src/capabilities/fission.rs
- fission-server/Cargo.toml
- fission-server/src/router.rs
- fission-server/src/routes/account.rs
- fission-server/src/routes/revocations.rs
This was specified to work like that in `design/api.md`, and the CLI actually already adds authentication to the request.
We... just never expected it. That's wrong, so this fixes it.
> fix: Authenticate the `GET /api/v0/account` endpoint

- design/api.md
- fission-core/src/common.rs
- fission-server/src/docs.rs
- fission-server/src/router.rs
- fission-server/src/routes/account.rs
As a replacement for returning the database ID in `GET /api/v0/account`.
This is easier to deprecate eventually and allowed some separation of concerns in the codebase.
> feat: Implement `GET /api/v0/account/member-number` endpoint

- README.md
- fission-server/Cargo.toml
- fission-server/README.md
- fission-server/src/main.rs
- fission-server/src/settings.rs
- fission-server/src/tracing_layers/format_layer.rs
- flake.nix
With this you can run the webserver using `nix run .`, but you'll need to specify the config path (unlike with `cargo run`), so make sure to pass it like this: `nix run . -- -c fission-server/config/settings.toml` or wherever your settings file resides.
This also changed the environment variable prefix used from `APP` to `FISSION_SERVER`, so e.g. you can set the path to the config file like this, too: `FISSION_SERVER__CONFIG_PATH="fission-server/config/settings.toml" nix run .`.
> chore: Better README & fix `nix run .`

- fission-cli/src/cli.rs
- fission-server/src/extract/authority.rs
- fission-server/src/middleware/logging.rs
- fission-server/src/router.rs
- fission-server/src/test_utils/route_builder.rs
Use the correct string for the header key, as per spec: https://github.com/ucan-wg/ucan-http-bearer-token#2-request-headers
Also set the header as allowed in the CORS settings.
> fix: Use `ucans` as header key, allow it in CORS

- .github/workflows/coverage.yml
- Cargo.lock
- Cargo.toml
- codecov.yml
- deny.toml
- fission-cli/Cargo.toml
- fission-cli/src/cli.rs
- fission-cli/src/main.rs
- fission-cli/src/settings.rs
- fission-cli/tests/cli.rs
- fission-cli/tests/main.rs
- fission-cli/tests/server.rs
- fission-server/Cargo.toml
- fission-server/src/extract/authority.rs
- fission-server/src/lib.rs
- fission-server/src/main.rs
- fission-server/src/models/capability_indexing.rs
- fission-server/src/routes/account.rs
- fission-server/src/routes/auth.rs
- fission-server/src/routes/capability_indexing.rs
- fission-server/src/routes/doh.rs
- fission-server/src/routes/health.rs
- fission-server/src/routes/ping.rs
- fission-server/src/routes/revocations.rs
- fission-server/src/setups/mod.rs
- fission-server/src/test_utils/ephermeral_db.rs
- fission-server/src/test_utils/mod.rs
- fission-server/src/test_utils/route_builder.rs
- fission-server/src/test_utils/test_context.rs
Main addition: Integration tests between the CLI and server in `fission-cli/tests/main.rs`.
Also:
- Add `--ephemeral-db` parameter to the server to use an ephemeral DB while running which is destroyed on close
- Add `--close-on-stdin-close` parameter to the server to enable listening on EOF in stdin and closing appropriately
- Add `--gen-key-if-needed` parameter to the server to enable writing a new key to the fs if there is none yet
- Added `--no-colors` CLI parameter to turn of colored output
- Added hidden `--key-seed` CLI parameter to enable isolating CLI tests
- Refactor server tests a bit. More `?` and less `&`, `TestContext::request` shorthand, etc.
> feat: Ephemeral DB mode & CLI integration tests

- .github/workflows/release.yml
- Cargo.toml
This replaces our (unused) google release please action with cargo-dist.
cargo-dist will build binaries for the CLI and server and create releases as artifacts.
> feat: Set up `cargo-dist` for binary releases
